---
kind: pipeline
name: python-3-9

steps:
- name: test
  image: python:3.9
  commands:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pytest --version
  - pytest

---
kind: pipeline
name: python-3-8

steps:
- name: test
  image: python:3.8
  commands:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pytest --version
  - pytest
  
---
kind: pipeline
name: python-2

steps:
- name: test
  image: python:2
  commands:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pytest --version
  - pytest
