---
kind: pipeline
name: go-1-11

steps:
- name: test
  image: golang
  commands:
  - ls -al
  - go version
  - go mod init example.com/hello 
  - go run ./helloworld.go
  - go get
  - go test
  - go build
 
